### PR TITLE
feat(secret): add secret support

### PR DESCRIPTION
**Pull request by Doster-d**
Оптимизируем вставки фурри картинок драконов.

### CODE REVIEW

**Comment by Kapu1178** [comment]
Isn't this a violation of AGPL v3?

**Comment by Crossedfall** [comment]
As per what Kapu noted, the license on this codebase and the upstream does explicitly prevent hosting modified changes without providing the full source.

> When a modified version is used to provide a service over a network, the complete source code of the modified version must be made available.

To be even more specific, you are bound by section 13 of the AGPL v3 license which states:

>  13. Remote Network Interaction; Use with the GNU General Public License.
>
 > Notwithstanding any other provision of this License, **if you modify the
Program, your modified version must prominently offer all users
interacting with it remotely through a computer network (if your version
supports such interaction) an opportunity to receive the Corresponding
Source of your version by providing access to the Corresponding Source
from a network server at no charge**, through some standard or customary
means of facilitating copying of software.  This Corresponding Source
shall include the Corresponding Source for any work covered by version 3
of the GNU General Public License that is incorporated pursuant to the
following paragraph.
>
 > Notwithstanding any other provision of this License, you have
permission to link or combine any covered work with a work licensed
under version 3 of the GNU General Public License into a single
combined work, and to convey the resulting work.  The terms of this
License will continue to apply to the part which is the covered work,
but the work with which it is combined will remain governed by version
3 of the GNU General Public License.

**Comment by TobyThorne** [comment]
Licensional comedy happened. 
Let's just pretend that at least any of this fork's contributors are aware of the license being a real thing and nuke this PR.

**Comment by Doster-d** [comment]
Пруф оф ворк получил, а замержим никогда.

**Pull request closed without merging**
